apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: rpb001/inventory  # Replace with your actual image name
          ports:
            - containerPort: 5100
          resources:
              requests:
                cpu: "1m"
              limits:
                cpu: "200m"