apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: ClusterIP
  selector:
    app: inventory
  ports:
    - protocol: TCP
      port: 5100  # External service port
      targetPort: 5100  # Port inside the container