apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: staging
spec:
  type: NodePort
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 5000  # External service port
      targetPort: 5000  # Port inside the container
      nodePort: 30012