apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: dev  # Set namespace to dev
spec:
  type: NodePort
  selector:
    app: inventory
  ports:
    - protocol: TCP
      port: 5100       # External service port
      targetPort: 5100  # Port inside the container
      nodePort: 30007   # NodePort (must be between 30000-32767)
