apiVersion: v1
kind: ConfigMap
metadata:
  name: coffee-config
  namespace: stage  # Change this based on your environment (prod/staging/dev)
data:
  ESPRESSO_SHOT_QUANTITY: "1000"
  MILK_FOAM_QUANTITY: "6000"
